apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-client-micronaut-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-client-micronaut-app
  template:
    metadata:
      labels:
        app: simple-client-micronaut-app
    spec:
      containers:
        - name: simple-client-micronaut-app
          image: simple-client-micronaut-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080